name: Tests

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
#    needs: build-and-push

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl auth init --access-token --expiry-seconds 600

      - name: test server docker
        run: docker ps