name: Tests

on: [ push ]

jobs:
  deploy:
    runs-on: ubuntu-latest
#    needs: build-and-push

    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: test server docker
        run: doctl docker ps