name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn test jacoco:report
        
        
      # set up xml path for code climate
      - name: set up xml path for code climate
        run: JACOCO_SOURCE_PATH=src/main/kotlin ./cc-test-reporter format-coverage ./target/site/jacoco/jacoco.xml --input-type jacoco

      # upload coverage on code climate
      - name: upload jacoco report
        run: ./cc-test-reporter upload-coverage -r ${{ secrets.CC_TEST_REPORTER_ID }}
