name: Tests

on: [ push ]

jobs:
  run-tests-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name:  Run tests & Publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
          JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/kotlin"
        with:
          coverageCommand: make test
          coverageLocations: ${{github.workspace}}/target/site/jacoco/jacoco.xml:jacoco
